"use strict";
/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".active[_ngcontent-%COMP%] {\n  color: orange; }\n\na[_ngcontent-%COMP%]:hover {\n  cursor: pointer; }\n\n.app-title[_ngcontent-%COMP%] {\n  width: 275px;\n  height: 60px;\n  float: left; }\n\n.app-title[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\n  padding: 10px;\n  text-align: center;\n  vertical-align: top;\n  font-size: 32px;\n  color: black;\n  display: inline-block; }\n\n#logo[_ngcontent-%COMP%] {\n  display: inline-block;\n  opacity: 0.8;\n  width: 75px;\n  height: 75px;\n  margin-top: -10px; }\n\n#menu-btn[_ngcontent-%COMP%] {\n  float: right; }\n\n@media (max-width: 550px) {\n  .app-title[_ngcontent-%COMP%] {\n    width: auto; }\n  .app-title[_ngcontent-%COMP%]   h1[_ngcontent-%COMP%] {\n    display: none; }\n  #logo[_ngcontent-%COMP%] {\n    width: 60px;\n    height: 60px;\n    margin-top: 0;\n    margin-left: 10px; } }"];
exports.styles = styles;
