"use strict";
/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["[_nghost-%COMP%] {\n  position: relative;\n  display: block;\n  width: 100%;\n  text-align: center; }\n\nh1[_ngcontent-%COMP%] {\n  position: fixed;\n  top: 40%;\n  left: 0;\n  right: 0;\n  font-size: 50px; }"];
exports.styles = styles;
