"use strict";
/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["[_nghost-%COMP%] {\n  position: relative;\n  display: block;\n  overflow-y: hidden;\n  overflow-x: hidden; }\n\ncore-section[_ngcontent-%COMP%] {\n  position: relative; }"];
exports.styles = styles;
