"use strict";
/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["footer[_ngcontent-%COMP%] {\n  position: fixed;\n  bottom: 0;\n  right: 0;\n  left: 0;\n  height: 25px;\n  background-image: url(\"/public/assets/footer.jpg\"); }\n\np[_ngcontent-%COMP%] {\n  color: white;\n  text-decoration: none;\n  display: inline-block;\n  line-height: 25px; }\n\n.octocat[_ngcontent-%COMP%] {\n  display: inline-block;\n  float: left;\n  height: 25px;\n  width: auto; }\n\n.github[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n  margin-left: 3px; }\n\n.devs[_ngcontent-%COMP%]:hover   p[_ngcontent-%COMP%], .github[_ngcontent-%COMP%]:hover   p[_ngcontent-%COMP%] {\n  text-decoration: underline; }\n\n.devs[_ngcontent-%COMP%] {\n  float: right;\n  margin-right: 5px; }"];
exports.styles = styles;
